include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  heimdex-processing-dlq {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }
  heimdex-caption-dlq {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }
  heimdex-stt-dlq {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }
  heimdex-ocr-dlq {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }
  heimdex-shorts-render-dlq {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }

  heimdex-processing-queue {
    defaultVisibilityTimeout = 120 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "heimdex-processing-dlq"
      maxReceiveCount = 3
    }
  }
  heimdex-caption-queue {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "heimdex-caption-dlq"
      maxReceiveCount = 5
    }
  }
  heimdex-stt-queue {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "heimdex-stt-dlq"
      maxReceiveCount = 5
    }
  }
  heimdex-ocr-queue {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "heimdex-ocr-dlq"
      maxReceiveCount = 3
    }
  }
  heimdex-shorts-render-queue {
    defaultVisibilityTimeout = 1800 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "heimdex-shorts-render-dlq"
      maxReceiveCount = 3
    }
  }
}
