"""Tests for the Phase 2.5a `/internal/videos/{file_id}/scenes-with-keyframes`
endpoint.

The router is gated behind ``drive_connector_enabled`` in main.py (the
endpoint reads keyframe S3 keys generated by drive-worker). These
tests exercise the router directly via FastAPI's TestClient + a
mounted app, bypassing the production gate so the endpoint logic is
testable without the full Drive subsystem booted.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock
from uuid import UUID, uuid4

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.modules.videos.internal_router import router as internal_router


def _build_app(
    *,
    drive_file_obj,
    scene_response: dict,
    internal_token: str = "test-internal-token",
) -> FastAPI:
    """Build a minimal FastAPI app with mocked dependencies so the
    endpoint can run in isolation."""
    from app.dependencies import (
        get_db_session,
        get_scene_opensearch_client,
        verify_internal_token,
    )

    fake_repo = MagicMock()
    fake_repo.get_by_id = AsyncMock(return_value=drive_file_obj)

    # The endpoint imports DriveFileRepository inside the handler.
    # Patch the class so the in-handler instantiation returns our fake.
    import app.modules.drive.repository as drive_repo_module
    drive_repo_module.DriveFileRepository = MagicMock(return_value=fake_repo)  # type: ignore[assignment]

    fake_scene_client = MagicMock()
    fake_scene_client.get_video_scenes = AsyncMock(return_value=scene_response)

    app = FastAPI()
    app.include_router(internal_router, prefix="/internal")

    # Replace dependencies with deterministic stubs.
    app.dependency_overrides[get_db_session] = lambda: AsyncMock()
    app.dependency_overrides[get_scene_opensearch_client] = lambda: fake_scene_client
    app.dependency_overrides[verify_internal_token] = lambda: internal_token

    return app


def _drive_file(*, file_id: UUID, video_id: str = "gd_abc123"):
    obj = MagicMock()
    obj.id = file_id
    obj.video_id = video_id
    return obj


# ---------- happy path ----------

def test_returns_chronologically_ordered_scenes_with_keyframe_keys():
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id, video_id="gd_abc123")

    # OS returns scenes deliberately out of order — the endpoint must
    # sort defensively (per the docstring contract).
    scene_response = {
        "scenes": [
            {
                "scene_id": "gd_abc123_scene_002",
                "start_ms": 30000, "end_ms": 45000,
                "keyframe_timestamp_ms": 37500,
            },
            {
                "scene_id": "gd_abc123_scene_001",
                "start_ms": 0, "end_ms": 30000,
                "keyframe_timestamp_ms": 15000,
            },
            {
                "scene_id": "gd_abc123_scene_003",
                "start_ms": 45000, "end_ms": 60000,
                "keyframe_timestamp_ms": None,
            },
        ],
    }
    app = _build_app(drive_file_obj=drive_file, scene_response=scene_response)
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["video_id"] == "gd_abc123"
    assert body["drive_file_id"] == str(file_id)
    assert body["total_duration_ms"] == 60000

    scenes = body["scenes"]
    assert [s["scene_id"] for s in scenes] == [
        "gd_abc123_scene_001",
        "gd_abc123_scene_002",
        "gd_abc123_scene_003",
    ], "endpoint must return scenes sorted by start_ms"

    # Keyframe S3 keys must use the canonical drive helper format.
    expected_prefix = f"{org_id}/drive/keyframes/gd_abc123/"
    for s in scenes:
        assert s["keyframe_s3_key"].startswith(expected_prefix)
        assert s["keyframe_s3_key"].endswith(".jpg")
    # Null-pass-through for keyframe_timestamp_ms when OS doesn't have it.
    assert scenes[2]["keyframe_timestamp_ms"] is None
    assert scenes[0]["keyframe_timestamp_ms"] == 15000


# ---------- auth ----------

def test_requires_bearer_token():
    file_id = uuid4()
    drive_file = _drive_file(file_id=file_id)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    # Don't override dependency this time — let the real
    # verify_internal_token reject the missing/wrong header.
    from app.dependencies import verify_internal_token
    app.dependency_overrides.pop(verify_internal_token, None)

    with TestClient(app) as client:
        # No Authorization header at all
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={"X-Heimdex-Org-Id": str(uuid4())},
        )
    assert resp.status_code in (401, 403, 422), (
        f"expected auth rejection, got {resp.status_code}"
    )


# ---------- 404 on missing video ----------

def test_returns_404_when_drive_file_missing():
    file_id = uuid4()
    org_id = uuid4()
    app = _build_app(
        drive_file_obj=None,    # repo returns None
        scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 404


# ---------- 400 on malformed org id ----------

def test_returns_400_on_invalid_org_id_header():
    file_id = uuid4()
    drive_file = _drive_file(file_id=file_id)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": "not-a-uuid",
            },
        )
    assert resp.status_code == 400


# ---------- empty + malformed scenes ----------

def test_empty_scene_list_returns_200_with_zero_scenes():
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["scenes"] == []
    assert body["total_duration_ms"] == 0


def test_drops_malformed_scene_rows_silently():
    """A row missing scene_id should be skipped, not 500. Defensive
    against partial OpenSearch reads or schema drift."""
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id, video_id="gd_x")
    scene_response = {
        "scenes": [
            {"scene_id": "gd_x_scene_001", "start_ms": 0, "end_ms": 1000, "keyframe_timestamp_ms": 500},
            {"start_ms": 1000, "end_ms": 2000},  # missing scene_id
            {"scene_id": "gd_x_scene_002", "start_ms": 2000, "end_ms": 3000, "keyframe_timestamp_ms": 2500},
        ],
    }
    app = _build_app(drive_file_obj=drive_file, scene_response=scene_response)
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    # Two valid scenes, malformed one dropped.
    assert len(body["scenes"]) == 2
    assert {s["scene_id"] for s in body["scenes"]} == {
        "gd_x_scene_001", "gd_x_scene_002",
    }
