"""Tests for the Phase 2.5a `/internal/videos/{file_id}/scenes-with-keyframes`
endpoint.

The router is gated behind ``drive_connector_enabled`` in main.py (the
endpoint reads keyframe S3 keys generated by drive-worker). These
tests exercise the router directly via FastAPI's TestClient + a
mounted app, bypassing the production gate so the endpoint logic is
testable without the full Drive subsystem booted.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock
from uuid import UUID, uuid4

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.modules.videos.internal_router import router as internal_router


@pytest.fixture
def _build_app(monkeypatch):
    """Build a minimal FastAPI app with mocked dependencies so the
    endpoint can run in isolation. Uses ``monkeypatch`` so the
    ``DriveFileRepository`` module-attribute override auto-reverts
    between tests — critical so the patch doesn't bleed into other
    test files (e.g., ``test_internal_drive_router.py``) that import
    the real class.
    """

    def _factory(
        *,
        drive_file_obj,
        scene_response: dict,
        internal_token: str = "test-internal-token",
    ) -> FastAPI:
        from app.dependencies import (
            get_db_session,
            get_scene_opensearch_client,
            verify_internal_token,
        )

        fake_repo = MagicMock()
        fake_repo.get_by_id_resource_scoped = AsyncMock(return_value=drive_file_obj)
        fake_repo.get_by_id = AsyncMock(return_value=drive_file_obj)

        import app.modules.drive.repository as drive_repo_module
        monkeypatch.setattr(
            drive_repo_module,
            "DriveFileRepository",
            MagicMock(return_value=fake_repo),
        )

        fake_scene_client = MagicMock()
        fake_scene_client.get_video_scenes = AsyncMock(return_value=scene_response)

        app = FastAPI()
        app.include_router(internal_router, prefix="/internal")

        app.dependency_overrides[get_db_session] = lambda: AsyncMock()
        app.dependency_overrides[get_scene_opensearch_client] = lambda: fake_scene_client
        app.dependency_overrides[verify_internal_token] = lambda: internal_token

        return app

    return _factory


def _drive_file(
    *,
    file_id: UUID,
    video_id: str = "gd_abc123",
    org_id: UUID | None = None,
    proxy_s3_key: str | None = "tenant-uuid/drive/drive-uuid/gfid/proxy.mp4",
):
    """Mocked DriveFile row. Pattern B endpoint derives ``org_id``
    from the resource itself, so the test fixture must populate
    ``obj.org_id`` (not just rely on the asserted header).

    ``proxy_s3_key`` defaults to a stable canonical-shaped value so
    the existing tests' assertions stay decoupled from this PR's
    new field. Tests that exercise the null path pass
    ``proxy_s3_key=None`` explicitly.
    """
    obj = MagicMock()
    obj.id = file_id
    obj.video_id = video_id
    obj.org_id = org_id if org_id is not None else uuid4()
    obj.proxy_s3_key = proxy_s3_key
    return obj


# ---------- happy path ----------

def test_returns_chronologically_ordered_scenes_with_keyframe_keys(_build_app):
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id, video_id="gd_abc123", org_id=org_id)

    # OS returns scenes deliberately out of order — the endpoint must
    # sort defensively (per the docstring contract).
    scene_response = {
        "scenes": [
            {
                "scene_id": "gd_abc123_scene_002",
                "start_ms": 30000, "end_ms": 45000,
                "keyframe_timestamp_ms": 37500,
            },
            {
                "scene_id": "gd_abc123_scene_001",
                "start_ms": 0, "end_ms": 30000,
                "keyframe_timestamp_ms": 15000,
            },
            {
                "scene_id": "gd_abc123_scene_003",
                "start_ms": 45000, "end_ms": 60000,
                "keyframe_timestamp_ms": None,
            },
        ],
    }
    app = _build_app(drive_file_obj=drive_file, scene_response=scene_response)
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["video_id"] == "gd_abc123"
    assert body["drive_file_id"] == str(file_id)
    assert body["total_duration_ms"] == 60000
    # ``proxy_s3_key`` is the canonical mp4 path the worker downloads
    # once per job. Verbatim mirror of ``DriveFile.proxy_s3_key`` —
    # never reconstruct in the endpoint.
    assert body["proxy_s3_key"] == "tenant-uuid/drive/drive-uuid/gfid/proxy.mp4"

    scenes = body["scenes"]
    assert [s["scene_id"] for s in scenes] == [
        "gd_abc123_scene_001",
        "gd_abc123_scene_002",
        "gd_abc123_scene_003",
    ], "endpoint must return scenes sorted by start_ms"

    # Keyframe S3 keys must use the canonical drive helper format.
    expected_prefix = f"{org_id}/drive/keyframes/gd_abc123/"
    for s in scenes:
        assert s["keyframe_s3_key"].startswith(expected_prefix)
        assert s["keyframe_s3_key"].endswith(".jpg")
    # Null-pass-through for keyframe_timestamp_ms when OS doesn't have it.
    assert scenes[2]["keyframe_timestamp_ms"] is None
    assert scenes[0]["keyframe_timestamp_ms"] == 15000


# ---------- auth ----------

def test_requires_bearer_token(_build_app):
    file_id = uuid4()
    drive_file = _drive_file(file_id=file_id)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    # Don't override dependency this time — let the real
    # verify_internal_token reject the missing/wrong header.
    from app.dependencies import verify_internal_token
    app.dependency_overrides.pop(verify_internal_token, None)

    with TestClient(app) as client:
        # No Authorization header at all
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={"X-Heimdex-Org-Id": str(uuid4())},
        )
    assert resp.status_code in (401, 403, 422), (
        f"expected auth rejection, got {resp.status_code}"
    )


# ---------- 404 on missing video ----------

def test_returns_404_when_drive_file_missing(_build_app):
    file_id = uuid4()
    org_id = uuid4()
    app = _build_app(
        drive_file_obj=None,    # repo returns None
        scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 404


# ---------- 400 on malformed org id ----------

def test_returns_400_on_invalid_org_id_header(_build_app):
    file_id = uuid4()
    drive_file = _drive_file(file_id=file_id)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": "not-a-uuid",
            },
        )
    assert resp.status_code == 400


# ---------- empty + malformed scenes ----------

def test_empty_scene_list_returns_200_with_zero_scenes(_build_app):
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id, org_id=org_id)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["scenes"] == []
    assert body["total_duration_ms"] == 0


# ---------- Pattern B (post-2026-05-01) auth ----------

def test_pattern_b_header_omitted_resolves_org_from_resource(_build_app):
    """Pattern B: ``X-Heimdex-Org-Id`` is OPTIONAL. The endpoint
    derives ``org_id`` from the DriveFile's own ``org_id`` and uses
    it to construct the keyframe S3 keys. This test pins the
    contract — bearer + path resource is sufficient."""
    file_id = uuid4()
    resource_org = uuid4()
    drive_file = _drive_file(
        file_id=file_id, video_id="gd_pb", org_id=resource_org,
    )
    scene_response = {
        "scenes": [
            {
                "scene_id": "gd_pb_scene_001",
                "start_ms": 0, "end_ms": 1000,
                "keyframe_timestamp_ms": 500,
            },
        ],
    }
    app = _build_app(drive_file_obj=drive_file, scene_response=scene_response)
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={"Authorization": "Bearer test-internal-token"},
        )
    assert resp.status_code == 200
    # S3 key must use the resource's org_id (not anything header-derived).
    assert resp.json()["scenes"][0]["keyframe_s3_key"].startswith(
        f"{resource_org}/drive/keyframes/gd_pb/"
    )


def test_pattern_b_header_mismatch_returns_404_not_403(_build_app):
    """Pattern B cross-validation: asserted org doesn't match the
    resource's org → 404 (not 403, not 400) so timing doesn't reveal
    the resource's true tenant."""
    file_id = uuid4()
    resource_org = uuid4()
    asserted_org = uuid4()
    drive_file = _drive_file(
        file_id=file_id, video_id="gd_pb", org_id=resource_org,
    )
    app = _build_app(drive_file_obj=drive_file, scene_response={"scenes": []})

    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(asserted_org),
            },
        )
    assert resp.status_code == 404
    assert resp.status_code != 403


def test_drops_malformed_scene_rows_silently(_build_app):
    """A row missing scene_id should be skipped, not 500. Defensive
    against partial OpenSearch reads or schema drift."""
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id, video_id="gd_x", org_id=org_id)
    scene_response = {
        "scenes": [
            {"scene_id": "gd_x_scene_001", "start_ms": 0, "end_ms": 1000, "keyframe_timestamp_ms": 500},
            {"start_ms": 1000, "end_ms": 2000},  # missing scene_id
            {"scene_id": "gd_x_scene_002", "start_ms": 2000, "end_ms": 3000, "keyframe_timestamp_ms": 2500},
        ],
    }
    app = _build_app(drive_file_obj=drive_file, scene_response=scene_response)
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    # Two valid scenes, malformed one dropped.
    assert len(body["scenes"]) == 2
    assert {s["scene_id"] for s in body["scenes"]} == {
        "gd_x_scene_001", "gd_x_scene_002",
    }


# ---------- proxy_s3_key field ----------

def test_proxy_s3_key_is_null_when_drivefile_has_no_proxy(_build_app):
    """Transcode-incomplete videos have ``proxy_s3_key=None`` on the
    DriveFile row. The endpoint passes through verbatim — null,
    not omitted. Worker maps this to a clean ``proxy_missing`` fail
    rather than the opaque ``internal_error``."""
    file_id = uuid4()
    org_id = uuid4()
    drive_file = _drive_file(file_id=file_id, org_id=org_id, proxy_s3_key=None)
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    body = resp.json()
    assert "proxy_s3_key" in body, "field must be present (explicit null), not omitted"
    assert body["proxy_s3_key"] is None


def test_proxy_s3_key_passes_through_canonical_drive_path_unchanged(_build_app):
    """Canonical layout: ``{org_id}/drive/{drive_id}/{google_file_id}/proxy.mp4``
    (heimdex_worker_sdk.drive_keys.proxy_s3_key). The endpoint does
    NOT reconstruct — it mirrors the DB column verbatim — so the
    test asserts the raw string is echoed regardless of shape. This
    locks the contract that no endpoint-side path massaging happens
    (drift between transcode-write and track-read would silently
    404 every download)."""
    file_id = uuid4()
    org_id = uuid4()
    canonical_key = (
        f"{org_id}/drive/2d0a3f2e-9999-4321-aaaa-111111111111/"
        f"1A2BcDeF_googleFileId/proxy.mp4"
    )
    drive_file = _drive_file(
        file_id=file_id, org_id=org_id, proxy_s3_key=canonical_key,
    )
    app = _build_app(
        drive_file_obj=drive_file, scene_response={"scenes": []},
    )
    with TestClient(app) as client:
        resp = client.get(
            f"/internal/videos/{file_id}/scenes-with-keyframes",
            headers={
                "Authorization": "Bearer test-internal-token",
                "X-Heimdex-Org-Id": str(org_id),
            },
        )
    assert resp.status_code == 200
    assert resp.json()["proxy_s3_key"] == canonical_key
