"""Add per-short summary columns to shorts_render_jobs.

Persists the 1-2 sentence Korean summary generated by
``shorts_render/summary_service.py`` (PR #177) so the saved-shorts
list and preview cards can display it WITHOUT firing an OpenAI call
per card per page view. The ``POST /api/shorts/render/{id}/summary``
endpoint becomes a generate/regenerate trigger that writes these
columns; ``GET /api/shorts/render`` then carries the summary for
free.

Three additive columns on ``shorts_render_jobs``:

* ``summary TEXT NULL`` — the generated summary text. NULL means
  "not yet generated" — the FE shows a 요약 생성 button for those
  rows.

* ``summary_prompt_version VARCHAR(16) NULL`` — the
  ``summary_prompt.PROMPT_VERSION`` in effect when the summary was
  generated. The service compares this against the current version
  on entry: a match means return the cached column, a mismatch (or
  NULL) means regenerate. Lets a prompt bump invalidate stale
  summaries without a backfill.

* ``summary_generated_at TIMESTAMPTZ NULL`` — when the summary was
  generated. Surfaced in the API response; also lets ops reason
  about staleness.

Strictly additive: every new column is nullable, every existing row
keeps NULL for all three. No backfill, no row touches. Mirrors the
additive style of migrations 056/057.

Revision ID: 059_add_render_summary
Revises: 058_widen_child_queue_index_for_self_heal
Create Date: 2026-05-14
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "059_add_render_summary"
down_revision: str | None = "058_widen_child_queue_index_for_self_heal"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Three additive columns. All nullable, no defaults — every
    # existing row stays NULL on each new column with no backfill.
    op.add_column(
        "shorts_render_jobs",
        sa.Column("summary", sa.Text(), nullable=True),
    )
    op.add_column(
        "shorts_render_jobs",
        sa.Column(
            "summary_prompt_version",
            sa.String(length=16),
            nullable=True,
        ),
    )
    op.add_column(
        "shorts_render_jobs",
        sa.Column(
            "summary_generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("shorts_render_jobs", "summary_generated_at")
    op.drop_column("shorts_render_jobs", "summary_prompt_version")
    op.drop_column("shorts_render_jobs", "summary")
